name: RSS-Bridge

on:
  schedule:
    - cron: '0 * * * *' # 매시간 실행
  workflow_dispatch:

jobs:
  rss_bridge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: |
          composer install

      - name: Run RSS-Bridge
        run: |
          docker run --rm rssbridge/rss-bridge:latest \
            /?action=display&bridge=Instagram&u=@sunaedong_buffet&media_type=all&format=Atom \
            > instagram_rss.xml

      - name: Upload RSS Feed
        uses: actions/upload-artifact@v4
        with:
          name: instagram_rss
          path: instagram_rss.xml

      - name: Generate RSS URL
        run: |
          echo "RSS Feed URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" > rss_link.txt

      - name: Upload RSS URL
        uses: actions/upload-artifact@v4
        with:
          name: rss_link
          path: rss_link.txt
