name: RSS-Bridge

on:
  schedule:
    - cron: '0 * * * *' # 매시간 실행
  workflow_dispatch:

jobs:
  rss_bridge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create RSS-Bridge Config
        run: |
          cat <<EOF > config.ini.php
          [system]
          whitelist_enabled = false
          EOF

      - name: Run RSS-Bridge
        run: |
          docker run --rm -v "$(pwd)/config.ini.php:/app/config.ini.php" \
            rssbridge/rss-bridge:2024-02-01 \
            "/?action=display&bridge=Instagram&u=sunaedong_buffet&media_type=all&format=Atom" \
            > instagram_rss.xml

      - name: Upload RSS Feed
        uses: actions/upload-artifact@v4
        with:
          name: instagram_rss
          path: instagram_rss.xml
